# Generated by Django 5.1.4 on 2025-04-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.CharField(max_length=100000000000)),
                ('response', models.CharField(max_length=100000000000)),
            ],
        ),
    ]
